version: '3.8'

services:
  fastapi-app:
    build: .
    image: pradeeptyagi23/tekocr:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Reference to the .env file
    depends_on:
      - redis-server

  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
