name: Python Linting, Type Checking, and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        elif [ -f pyproject.toml ]; then
          pip install .
        else
          pip install flake8 mypy
        fi

    - name: Run flake8
      run: flake8 .

    - name: Run mypy
      run: mypy .

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image with Docker Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker tag tekocr:latest pradeeptyagi23/tekocr:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push pradeeptyagi23/tekocr:latest
